name: workflow totalization

on:
  workflow_dispatch:
    inputs:
      method:
        description: '直近1ヶ月を取得するか、手動で取得期間を入力するか選択してください'
        required: true
        default: '1month'
        type: choice
        options:
        - 1month
        - manual
      daystart:
        description: '[manual選択時]実績状況の取得開始日をyyyy-MM-ddで入力してください。（例：2022-10-26）'
        type: string
      dayend:
        description: '[manual選択時]実績状況の取得終了日をyyyy-MM-ddで入力してください。（例：2022-10-28）'
        type: string

permissions:
  contents: read

jobs:
  workflowtotalization:
    runs-on: ubuntu-latest
    steps:   
      - name: created settings
        if: ${{ github.event.inputs.method == '1month' }}
        run: |
          echo "CREATED=>2022-10-19" >> $GITHUB_ENV
          :
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              created: ${{ env.CREATED }}
            })
            
            var worlflows = {};
            let output = "";
            for(let workflow of result.data.workflow_runs){
              let id = workflow.id;
              const run = await github.rest.actions.listJobsForWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: workflow.id,
              });              
              var date1 = new Date(run.data.jobs[0].started_at);
              var date2 = new Date(run.data.jobs[0].completed_at);

              output +=  workflow.name + " : " + (date2.getTime() - date1.getTime()) + "<br>";
            }
            
            await core.summary
              .addHeading('Workflows report')
              .addRaw(output)
              .write()
