name: workflow totalization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflowtotalization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const octokit = new Octokit({
              auth: context.github.token
            })
            const workflows = await octokit.request('GET /repos/context.github.repository_owner/context.github.repository/actions/workflows'})
            console.log(workflows)
