name: workflow totalization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflowtotalization:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              created: '>2022-10-19'
            })
            
            var worlflows = {};
            for(let workflow of result.data.workflow_runs){
              let id = workflow.id;
              if(!worlflows[id]){
                worlflows[id] = 0;
              }
              console.log(worlflows[id]);

              const run = await github.rest.actions.listJobsForWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: workflow.id,
              });              
              var date1 = new Date(run.data.jobs[0].started_at);
              var date2 = new Date(run.data.jobs[0].completed_at);
              worlflows[id] += (date2.getTime() - date1.getTime());
            }
            
            let output = "";
            for(key i of worlflows)
            {
              output += key + " : " + worlflows[i] + "<br>";
            }
            
            await core.summary
              .addHeading('Workflows report')
              .addRaw(output)
              .write()
