name: workflow totalization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflowtotalization:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/github-script@v6
        with:
          script: |
            const workflows = github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for(workflow in workflows){
              console.log(workflow.id);
              console.log(workflow.name);
            }
            
