name: workflow totalization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflowtotalization:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              created: '>2022-10-19'
            })
            console.log(JSON.stringify(result));
            
            let output = "";
            for(let workflow of result.data.workflow_runs){
              output += workflow.name + ":";
              output += workflow.workflow_id + "<br>";
              
            }
            await core.summary
              .addHeading('Workflows report')
              .addRaw(output)
              .write()
