name: workflow totalization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflowtotalization:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            let output = "";
            for(let workflow of result.data.workflows){
              output += workflow.id + "<br>";
              output += workflow.name + "\n  ";
              output += workflow.path + "<br>";
            }
            await core.summary
              .addHeading('Workflows report')
              .addRaw(output)
              .write()
