name: workflow totalization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflowtotalization:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log(JSON.stringify(result.data));
            const output = "XXX";
            for(const workflow of result){
              output = output + "1つ";
              output = output + workflow.id + "\n";
              output = output + workflow.name + "\n";
            }
            await core.summary
              .addHeading('Workflows report')
              .addRaw(output)
              .write()
