name: workflow totalization

on:
  workflow_dispatch:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  workflowtotalization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install @octokit/action
    
      - uses: actions/github-script@v6
        with:
          script: |
            const workflows = github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
