name: workflow totalization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflowtotalization:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              created: '>2022-10-19'
            })
            var worlflows = {};
            let output = "";
            for(let workflow of result.data.workflow_runs){
              let id = workflow.id;
              if(!worlflows[id]){
                worlflows[id] = 0;
              }

              const run = await github.rest.actions.listJobsForWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: workflow.id,
              });
              
              console.log(JSON.stringify(run.data.jobs.started_at));
              console.log(JSON.stringify(run.data.jobs.completed_at));
              
              var date1 = new Date(run.data.jobs.started_at);
              console.log(data1);
              var date2 = new Date(run.data.jobs.completed_at);
              console.log(data2);
              worlflows[id] += date2.getTime() - date1.getTime();

              output += workflow.name + ":";
              output += workflow.workflow_id + "<br>";
              output += worlflows[id] + "<br>";
            }
            await core.summary
              .addHeading('Workflows report')
              .addRaw(output)
              .write()
