name: workflow totalization

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflowtotalization:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const octokit = new Octokit({
              auth: "${{ secrets.GITHUB_TOKEN }}"
            })

            const workflows = await octokit.request('GET /repos/{owner}/{repo}/actions/workflows', {
              owner: context.github.repository_owner
              repo: context.github.repository
            })
            
            console.log(workflows)
